name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@add3486cc3b55d4a5e11c8045058cef96538edc7
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@76d3665dc084409ba9e6c467009338cf86e9dd5f
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
